name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer install
      run: cd project/ && composer install  && php bin/console make:migration

   - name: C
    run: cd project/ && php bin/console doctrine:database:create
    
   - name: Database 2
    run: cd project/ && php bin/console doctrine:migrations:migrate




