name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer install
      run: cd project/ && composer install  

    - name: C
      run: cd project/ && php bin/console doctrine:database:create
    




